gpt:
  apiKeys:
    - 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
  maxPreContextNum:
    10
  proxyType: #代理类型
    2
  ip:
    127.0.0.1
  port:
    10886 # 1080
  storeMessage:
    100
server:
  port: 8081

logging:
  file:
    name: "./logs/chat_log.txt"

# 配置redis需要的信息
spring:
  redis:
    host: 82.156.167.18
    port: 6379
    password: 123456
    database: 0
